export const homeData = [
  {
    id: 1,
    title: "project del sol",
    imageMobile: "/portfolio/mobile/image-del-sol.jpg",
    imageDesktop: "/portfolio/desktop/image-del-sol.jpg",
  },
  {
    id: 2,
    title: "228B tower",
    imageMobile: "/portfolio/mobile/image-228b.jpg",
    imageDesktop: "/portfolio/desktop/image-228b.jpg",
  },
  {
    id: 3,
    title: "le prototype",
    imageMobile: "/portfolio/mobile/image-prototype.jpg",
    imageDesktop: "/portfolio/desktop/image-prototype.jpg",
  },
];

export const portfolioData = [
  {
    id: 1,
    title: "seraph station",
    imageMobile: "/portfolio/mobile/image-seraph.jpg",
    imageTablet: "/portfolio/tablet/image-seraph.jpg",
    imageDesktop: "/portfolio/desktop/image-seraph.jpg",
    date: "september 2019",
  },
  {
    id: 2,
    title: "eebox building",
    imageMobile: "/portfolio/mobile/image-eebox.jpg",
    imageTablet: "/portfolio/tablet/image-eebox.jpg",
    imageDesktop: "/portfolio/desktop/image-eebox.jpg",
    date: "august 2017",
  },
  {
    id: 3,
    title: "federal II tower",
    imageMobile: "/portfolio/mobile/image-federal.jpg",
    imageTablet: "/portfolio/tablet/image-federal.jpg",
    imageDesktop: "/portfolio/desktop/image-federal.jpg",
    date: "march 2017",
  },
  {
    id: 4,
    title: "project del sol",
    imageMobile: "/portfolio/mobile/image-del-sol.jpg",
    imageTablet: "/portfolio/tablet/image-del-sol.jpg",
    imageDesktop: "/portfolio/desktop/image-del-sol.jpg",
    date: "january 2016",
  },
  {
    id: 5,
    title: "le prototype",
    imageMobile: "/portfolio/mobile/image-prototype.jpg",
    imageTablet: "/portfolio/tablet/image-prototype.jpg",
    imageDesktop: "/portfolio/desktop/image-prototype.jpg",
    date: "october 2015",
  },
  {
    id: 6,
    title: "228B tower",
    imageMobile: "/portfolio/mobile/image-228b.jpg",
    imageTablet: "/portfolio/tablet/image-228b.jpg",
    imageDesktop: "/portfolio/desktop/image-228b.jpg",
    date: "april 2015",
  },
  {
    id: 7,
    title: "grand edelweiss hotel",
    imageMobile: "/portfolio/mobile/image-edelweiss.jpg",
    imageTablet: "/portfolio/tablet/image-edelweiss.jpg",
    imageDesktop: "/portfolio/desktop/image-edelweiss.jpg",
    date: "december 2013",
  },
  {
    id: 8,
    title: "netcry tower",
    imageMobile: "/portfolio/mobile/image-netcry.jpg",
    imageTablet: "/portfolio/tablet/image-netcry.jpg",
    imageDesktop: "/portfolio/desktop/image-netcry.jpg",
    date: "august 2012",
  },
  {
    id: 9,
    title: "hypers",
    imageMobile: "/portfolio/mobile/image-hypers.jpg",
    imageTablet: "/portfolio/tablet/image-hypers.jpg",
    imageDesktop: "/portfolio/desktop/image-hypers.jpg",
    date: "january 2012",
  },
  {
    id: 10,
    title: "SXIV tower",
    imageMobile: "/portfolio/mobile/image-sxiv.jpg",
    imageTablet: "/portfolio/tablet/image-sxiv.jpg",
    imageDesktop: "/portfolio/desktop/image-sxiv.jpg",
    date: "march 2011",
  },
  {
    id: 11,
    title: "trinity bank tower",
    imageMobile: "/portfolio/mobile/image-trinity.jpg",
    imageTablet: "/portfolio/tablet/image-trinity.jpg",
    imageDesktop: "/portfolio/desktop/image-trinity.jpg",
    date: "september 2010",
  },
  {
    id: 12,
    title: "project paramour",
    imageMobile: "/portfolio/mobile/image-paramour.jpg",
    imageTablet: "/portfolio/tablet/image-paramour.jpg",
    imageDesktop: "/portfolio/desktop/image-paramour.jpg",
    date: "february 2008",
  },
];

export const leaders = [
  {
    id: 1,
    name: "Jake Richards",
    title: "Chief Architect",
    image: "/about/desktop/avatar-jake.jpg",
  },
  {
    id: 2,
    name: "Thompson Smith",
    title: "Head of Finance",
    image: "/about/desktop/avatar-thompson.jpg",
  },
  {
    id: 3,
    name: "Jackson Rourke",
    title: "Lead Designer",
    image: "/about/desktop/avatar-jackson.jpg",
  },
  {
    id: 4,
    name: "Maria Simpson",
    title: "Senior Architect",
    image: "/about/desktop/avatar-maria.jpg",
  },
];
